### ISSUE TITLE
'tech_bias' function without spike-ins?

### ISSUE THREAD

**Issue by kbchoi-jax** [yuchaojiang/SCALE#1]
Hi Yuchao,

How do I get alpha, beta, kappa, and tau when I do not have spike-ins?

`abkt=tech_bias(spikein_input=spikein_input, alleleA = alleleA, 
               alleleB = alleleB, readlength = 50, pdf=FALSE)
`

Thanks,

**Comment by yuchaojiang** [comment]
Hey KB,

If you do not have spike-ins in your scRNA-seq dataset, you should still adopt other denoising/imputation methods for data normalization. The technical dropout affects the estimation of burst frequency and the amplification bias affects the estimation of burst size.

Supposed you have a normalized gene expression matrix, you can pre-specify log(alpha), beta, kappa, and tau to be log(1), 1, 10000, 0 so SCALE does not perform another round of normalization.

`abkt = c(0, 1, 10000, 0); names(abkt) = c("log(alpha)", "beta", "kappa", "tau") `

**Comment by rcosentino** [comment]
Hi Yuchao,

I am trying to pre-specify abkt as you indicate above, but when I run "allelic_kinetics" I get the following error message:
```
Error in if (sum(nc.temp[-1]) > num.cells) { : 
  missing value where TRUE/FALSE needed
```
I played around a little bit and noticed that if I put instead a negative value for log(alpha), like -1 or -100 or -0.01 , it runs through..

I also tried to run your demo data using the pre-set abkt as you indicate above and I get the same error message..

What do you think?

Cheers,

Raúl

**Comment by yuchaojiang** [comment]
Hi Raul,

Have you performed any normalization? While it is hard to pinpoint what is wrong with the error message you sent, it feels to me that the data may be under normalized.

Yuchao

**Comment by yuchaojiang** [comment]
> Hi Yuchao,
> 
> I am trying to pre-specify abkt as you indicate above, but when I run "allelic_kinetics" I get the following error message:
> 
> ```
> Error in if (sum(nc.temp[-1]) > num.cells) { : 
>   missing value where TRUE/FALSE needed
> ```
> 
> I played around a little bit and noticed that if I put instead a negative value for log(alpha), like -1 or -100 or -0.01 , it runs through..
> 
> I also tried to run your demo data using the pre-set abkt as you indicate above and I get the same error message..
> 
> What do you think?
> 
> Cheers,
> 
> Raúl

We've run into a similar issue and have updated the code to resolve this. Essentially it led to a log(0) underflow problem.
