### ISSUE TITLE
tech_bias function error

### ISSUE THREAD

**Issue by rberrens** [yuchaojiang/SCALE#2]
I am trying to compute the tech_bias in my dataset with SCALE. I converted the spikein_input to have the same format as in the example dataset and made sure all the columns are in numeric format in my dataframe:
spikein_input
'data.frame':	92 obs. of  68 variables:
 $ spikein_mol   : num  3.00e+04 1.88e+03 1.88e+03 9.38e+02 1.72e-01 ...
 $ spikein_length: num  1061 1023 523 984 994 ...
 $ nufh3_3       : num  2250 251 894 92 0 0 0 0 0 0 ...
 $ nufh3_4       : num  1375 101 324 19 0 ...
 $ nufh3_6       : num  1127 120 403 116 0 ...
 $ nufh3_8       : num  1464 154 530 81 0 ...
 $ nufh3_9       : num  467 85 175 8 0 0 0 0 0 0 ...
 $ nufh3_10      : num  354 54 171 8 0 0 0 0 0 0 ...
 $ nufh3_11      : num  457 11 138 44 0 0 14 0 0 4 ...
 $ nufh3_12      : num  451 41 193 29 0 0 0 0 0 0 ...

alleleA
'data.frame':	60609 obs. of  66 variables:
 $ nufh3_3 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_4 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_6 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_8 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_9 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_10: num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_11: num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_12: num  0 0 0 0 0 0 0 0 0 0 ...

alleleB
'data.frame':	60609 obs. of  66 variables:
 $ nufh3_3 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_4 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_6 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_8 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_9 : num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_10: num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_11: num  0 0 0 0 0 0 0 0 0 0 ...
 $ nufh3_12: num  0 0 0 0 0 0 0 0 0 0 ...

However when I am running the tech_bias function I am getting the following issue: Error in dpois(round(Q[i]), (lambda[i]), log = TRUE) : Non-numeric argument to mathematical function.
With Traceback: 

5. | dpois(round(Q[i]), (lambda[i]), log = TRUE)
4. fn(par,...)
3. (function (par) fn(par, ...))(c(-2,2))
2.optim(par=kappa.tau, function(kappa.tau) { kappa=kappatau[1] tau=kappa.tau[2] l =0 ...
1. tech_bias(spikein_input = spikein_input, alleleA = alleleA, alleleB = alleleB, readlength=50, pdf=FALSE)
![image](https://user-images.githubusercontent.com/7227823/76091934-6ddb5a00-5fb6-11ea-9755-4fa2c0a478f5.png)

Can you give me any advice regarding this issue?

**Comment by yuchaojiang** [comment]
Hi

Can you send me your data input for the tech bias step? It’s hard to tell what’s wrong with the info you provided.

Yuchao


On Mar 6, 2020, at 9:18 AM, Rebecca Berrens <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to compute the tech_bias in my dataset with SCALE. I converted the spikein_input to have the same format as in the example dataset and made sure all the columns are in numeric format in my dataframe:
spikein_input
'data.frame': 92 obs. of 68 variables:
$ spikein_mol : num 3.00e+04 1.88e+03 1.88e+03 9.38e+02 1.72e-01 ...
$ spikein_length: num 1061 1023 523 984 994 ...
$ nufh3_3 : num 2250 251 894 92 0 0 0 0 0 0 ...
$ nufh3_4 : num 1375 101 324 19 0 ...
$ nufh3_6 : num 1127 120 403 116 0 ...
$ nufh3_8 : num 1464 154 530 81 0 ...
$ nufh3_9 : num 467 85 175 8 0 0 0 0 0 0 ...
$ nufh3_10 : num 354 54 171 8 0 0 0 0 0 0 ...
$ nufh3_11 : num 457 11 138 44 0 0 14 0 0 4 ...
$ nufh3_12 : num 451 41 193 29 0 0 0 0 0 0 ...

alleleA
'data.frame': 60609 obs. of 66 variables:
$ nufh3_3 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_4 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_6 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_8 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_9 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_10: num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_11: num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_12: num 0 0 0 0 0 0 0 0 0 0 ...

alleleB
'data.frame': 60609 obs. of 66 variables:
$ nufh3_3 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_4 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_6 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_8 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_9 : num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_10: num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_11: num 0 0 0 0 0 0 0 0 0 0 ...
$ nufh3_12: num 0 0 0 0 0 0 0 0 0 0 ...

However when I am running the tech_bias function I am getting the following issue: Error in dpois(round(Q[i]), (lambda[i]), log = TRUE) : Non-numeric argument to mathematical function.
With Traceback:

  1.  | dpois(round(Q[i]), (lambda[i]), log = TRUE)
  2.  fn(par,...)
  3.  (function (par) fn(par, ...))(c(-2,2))
2.optim(par=kappa.tau, function(kappa.tau) { kappa=kappatau[1] tau=kappa.tau[2] l =0 ...
  4.  tech_bias(spikein_input = spikein_input, alleleA = alleleA, alleleB = alleleB, readlength=50, pdf=FALSE)

Can you give me any advice regarding this issue?

**Comment by yuchaojiang** [comment]
Closing this issue. If you need further assistance, feel free to open again.
