### ISSUE TITLE
Issue running allelic_kinetics()

### ISSUE THREAD

**Issue by rberrens** [yuchaojiang/SCALE#3]
When I am running alleleic_kinetics with setting a cellsize vector with all values =1. I get the error Error in if (sum(nc.temp[-1]) > num.cells) { : 
  missing value where TRUE/FALSE needed

**Comment by yuchaojiang** [comment]
Hi, again it's hard to tell what's wrong with only the error message. We did recently made an update to the allelic_kinetics function to prevent underflow. Please update the package through GitHub and give another try. If you need further help, we need a demo dataset with more detailed information.
