### ISSUE TITLE
Running SCALE without spikeinn

### ISSUE THREAD

**Issue by Hemantcnaik** [yuchaojiang/SCALE#5]
Hello,
   I am doing single cell allelic kinetics analysis don't have the spike in information in my data. So  looking for allelic normalization not able find any method. can you please suggest me any method for normalization. For SCALE mentioned as normalization is important. previous issue discussed about this but tried search for various method didn't find any. can you please mention any method for allele normalization can be used for SCALE analysis.

**Comment by yuchaojiang** [comment]
Hi,

You can use DESCEND (https://www.pnas.org/content/115/28/E6437) to recover the true distribution of allelic coverage. We don't have a readily available script for this yet but are planning on releasing this soon.
