### ISSUE TITLE
About cell size calculation

### ISSUE THREAD

**Issue by srishastry123** [yuchaojiang/SCALE#6]
Hello,,

Thanks for the Tool , currently I ran the SCALE analysis on my allele specific single cell data successfully.  I have question in cell size calculation. have single cell mapped read RNA seq readcount as well as allele specific RNA seq readcount. which one will be good for cell size calculation below mentioned some piece of code in R for cell size can you suggest me which is correct or not.

cell_size= colSums(single_cell_readcount)/colSumns(spikein_read_count)
or
cell_size= colSums(AlleleA+AlleleB)/colSumns(spikein_read_count)

and allso one more question what is the Ideal number cell for SCALE analysis. because in my data after kinetics analysis graph showing R=0.88 for Burst frequency and for burst size R is very low near to 0.31 can you comment on this result.
your help will be very greatfull

Thank you

**Comment by srishastry123** [comment]
How to interpret allelic independence using the P-value(pval.ind) column in SCALE output

**Comment by yuchaojiang** [comment]
> Hello,,
> 
> Thanks for the Tool , currently I ran the SCALE analysis on my allele specific single cell data successfully. I have question in cell size calculation. have single cell mapped read RNA seq readcount as well as allele specific RNA seq readcount. which one will be good for cell size calculation below mentioned some piece of code in R for cell size can you suggest me which is correct or not.
> 
> cell_size= colSums(single_cell_readcount)/colSumns(spikein_read_count)
> or
> cell_size= colSums(AlleleA+AlleleB)/colSumns(spikein_read_count)
> 
> and allso one more question what is the Ideal number cell for SCALE analysis. because in my data after kinetics analysis graph showing R=0.88 for Burst frequency and for burst size R is very low near to 0.31 can you comment on this result.
> your help will be very greatfull
> 
> Thank you

Hi,

I don't think the two would differ too much -- in the end, you would need to center your cell size factor to be around one (the denominators are the same and the numerators are highly correlated).

**Comment by yuchaojiang** [comment]
> How to interpret allelic independence using the P-value(pval.ind) column in SCALE output

It tests whether the two alleles burst independently and there's an additional column on whether it is coordinated bursting or repulsed bursting.

gene name
gene category (see our paper for more details)
burst frequency for A allele
burst frequency for B allele
p-value for testing differential burst frequency
burst size for A allele
burst size for B allele
p-value for testing differential burst size
Number of cells expressing A allele
Number of cells expressing B allele
Number of cells expressing AB allele
Number of cells expressing neither allele
Proportion of cells expressing A allele
Proportion of cells expressing B allele
p-value for independent bursting
non-independent bursting time (C for coordinates; R for repulsed)

**Comment by srishastry123** [comment]
Thanks for your response 
can you comment on the below output
[result.pdf](https://github.com/yuchaojiang/SCALE/files/5003533/result.pdf)

**Comment by srishastry123** [comment]
A file generated after allelic.kinetics
