### ISSUE TITLE
How to interpret the indipendence and non-indipendence 

### ISSUE THREAD

**Issue by srishastry123** [yuchaojiang/SCALE#7]
Hello,
I was going through a question on scale out put based  on P-value Significant  means Independent and P-value  Non-significant is Non-independent  is it a right way of interpretation, can you please explain me how this works..

Thank you

**Comment by yuchaojiang** [comment]
No. You can look up the definition for p-value. The null hypothesis is independent bursting; the alternative is non-independent bursting.
