### ISSUE TITLE
Finding Significant different burst frequencies  pval.kon and pval.size

### ISSUE THREAD

**Issue by srishastry123** [yuchaojiang/SCALE#8]
Helo

Yuchao 

 For Finding Significant Differential bursting frequencies and size in column pval.kon and pval.size the threshold  significant  <= 0.05 is enough. I got a doubt because in SCALE paper mentioned after the FDR control identified the significant genes. and is it pval.kon and pval.size is FDR control p values 
for FDR what method you used I was goiing through this below script understand can you please suggest me what method 

if(min(pval.kon)<=(0.05/length(ind.genes))){
    kon.thres=max(which(sort(pval.kon)-1:length(ind.genes)/length(ind.genes)*0.05<0))/length(ind.genes)*0.05
} else{
    kon.thres=-Inf
}

if(min(pval.size)<=(0.05/length(ind.genes))){
    size.thres=max(which(sort(pval.size)-1:length(ind.genes)/length(ind.genes)*0.05<0))/length(ind.genes)*0.05
} else{
    size.thres=-Inf
}

sig.kon.index=c(which(pval.kon<=kon.thres))
sig.size.index=c(which(pval.size<=size.thres))

**Comment by yuchaojiang** [comment]
You can use the qvalue package from bioconductor to carry out FDR control
