### ISSUE TITLE
Suggestion for doing allele specific analysis for mouse data set

### ISSUE THREAD

**Issue by luckysardar** [yuchaojiang/SCALE#9]
Hello  I have mouse data set wanted do the Scale analysis.  In your bioinfo script mentioned for human data how to caluculate allele count. for mouse data set how can we get the allele specific analysis any standard method for allelic analysis I went through Deng et al. 2014  paper which you taken sample data set with there method I got the per SNP site wise allele count. but for gene wise allele count what exactly we have to do.  taking sum of all the count across snp for a gene will give the allele count for gene  or taking average will.

 can you please suggest me how can  proceed with this methodology

**Comment by yuchaojiang** [comment]
The bioinformatic pipeline stays the same (you just need to update the reference genome and the annotations etc)
To get one SNP for a gene, we pick the one with the highest average read count across all cells.
